name: Expressions & Contexts
on: [push, pull_request, issues, workflow_dispatch]
run-name: "Expressions & Contexts by @${{ github.actor }}, event: ${{ github.event_name }}"
jobs:
  using-expressions-and-contexts:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Expressions
        id: expressions
        run: |
          echo ${{ 1 }}
          echo ${{ 'This is a string' }}
          echo ${{ null }}
          echo ${{ true }}
          echo ${{ 1 > 2 }}
          echo ${{ 'string' == 'String' }}
          echo ${{ true && false }}
          echo ${{ true || (false && true) }}
      - name: Dump Contexts
        run: |
          echo '${{ toJson(github) }}'
          echo '${{ toJson(job) }}'
          echo '${{ toJson(secrets) }}'
          echo '${{ toJson(steps) }}'
          echo '${{ toJson(runner) }}'
