name: Reusable Workflow
on:
  workflow_call:
    outputs:
      date:
        description: "Date Value"
        value: ${{ jobs.generate-output.outputs.date }}

jobs:
  generate-output:
    runs-on: ubuntu-latest
    outputs:
      date: ${{ steps.date-step.outputs.date }}
    steps:
      - run: echo "date=$(date)" >> $GITHUB_OUTPUT
        id: date-step
